require "Googleplay_InAppBilling_PurchaseVeryfication/version"
require 'Googleplay_InAppBilling_PurchaseVeryfication/config'
require 'Googleplay_InAppBilling_PurchaseVeryfication/play'

module GoogleplayInAppBillingPurchaseVeryfication

end
